name: piu CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('**/deps.edn') }}
    - uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: '21.0.0.java11'
    - uses: DeLaGuardo/setup-clojure@master
      with:
        tools-deps: '1.10.1.763'
    - run: gu install native-image
    - run: make compile
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: piu
        asset_name: piu-linux-amd64
        tag: ${{ github.ref }}
        overwrite: true
