name: piu CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          m2-
    - uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: 'vm-22.3.3'
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.11.1.1347'
    - run: gu install native-image
    - run: gu install js
    - run: make compile
    - name: "Generate tag"
      run: |
        COMMIT_DATE=$(git show -s --format=%cd --date=format:%y%m%d-%H%M HEAD)
        echo "tag_name=${COMMIT_DATE}" >> $GITHUB_ENV
        mv piu piu-linux-amd64
        gzip piu-linux-amd64
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: piu-linux-amd64.gz
        tag_name: ${{ env.tag_name }}
