name: piu CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: buildjet/cache@v4
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          m2-
    - uses: sdkman/sdkman-action@main
      id: sdkman
    - run: java -version
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.12.2.1565'
    - run: make native
    - name: "Generate tag"
      run: |
        COMMIT_DATE=$(git show -s --format=%cd --date=format:%y%m%d-%H%M HEAD)
        echo "tag_name=${COMMIT_DATE}" >> $GITHUB_ENV
        mv piu piu-linux-amd64
        gzip piu-linux-amd64
    - name: Publish release
      uses: softprops/action-gh-release@v2
      with:
        files: piu-linux-amd64.gz
        tag_name: ${{ env.tag_name }}
