name: piu CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('**/deps.edn') }}
    - uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '20.1.0.java11'
    - uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.645'
    - run: gu install native-image
    - run: make compile
    - uses: actions/upload-artifact@v1
      with:
        name: piu
        path: piu
